[BinderHub](https://github.com/jupyterhub/binderhub) failed to launch <failed-repository-url>.

## What is the current bug behavior?

<!-- Paste the build logs -->

## What is the expected correct behavior?

BinderHub launches container successfuly.

## Steps to reproduce

1. Visit https://notebooks.gesis.org/binder/
2. Fill `URL` with <failed-repository-url>
3. Click `launch`

## Reproducible at ovh.mybinder.org

1. Visit https://ovh.mybinder.org/
2. Fill `URL` with <failed-repository-url>
3. Click `launch`

resulted in <!-- same issue / different issue / no issue -->.
